In [3]:
import numpy as np
import pandas as pd

step_angle=90
angles=np.arange(90,360,step_angle)
print(angles)

data=pd.read_csv("data/multitool_topToolTipPnts.csv")

for angle in angles:
    #const
    sin=np.sin(angle*np.pi/180)
    cos=np.cos(angle*np.pi/180)
    data["radio"] = (data.X**2+data.Y**2)**0.5
    data["X"+str(angle)]=cos*data.radio
    data["Y"+str(angle)]=sin*data.radio

data.head()

[ 90 180 270]

,X,Y,Z,radio,X90,Y90,X180,Y180,X270,Y270
0,92.0223,-0.0000,-0.0209,92.022300,5.634741e-15,92.022300,-92.022300,1.126948e-14,-1.690422e-14,-92.022300
1,92.0219,0.2718,-0.0209,92.022301,5.634741e-15,92.022301,-92.022301,1.126948e-14,-1.690422e-14,-92.022301
2,92.0136,1.2699,-0.0209,92.022363,5.634745e-15,92.022363,-92.022363,1.126949e-14,-1.690423e-14,-92.022363
3,91.9944,2.2678,-0.0209,92.022348,5.634744e-15,92.022348,-92.022348,1.126949e-14,-1.690423e-14,-92.022348
4,91.9644,3.2655,-0.0209,92.022358,5.634744e-15,92.022358,-92.022358,1.126949e-14,-1.690423e-14,-92.022358